title: " " 
author: Anna Sterzik, John Wigg, Sebastian Ebert
email: anna.sterzik@uni-jena.de, john.wigg@uni-jena.de, sebastian.ebert@uni-jena.de
description: > # this means to ignore newlines until "twitter_username:"
  This checklist was created in the module: "Management of Scientific Data" and should give you 
  an overview on how to describe your dataset and workflows, the way the future you and other 
  researchers are able to use it.

# Site settings
theme: minima
plugins:
  - jekyll-title-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
